# Generated by Django 6.0 on 2025-12-26 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('level', models.IntegerField(choices=[(0, 'Lv0 - 戦力外'), (1, 'Lv1 - 最優先'), (2, 'Lv2 - 通常'), (3, 'Lv3 - なるべく避ける'), (4, 'Lv4 - 原則避ける')], default=2, verbose_name='レベル')),
                ('department', models.CharField(choices=[('食品', '食品'), ('非食品', '非食品'), ('その他', 'その他')], default='食品', max_length=20, verbose_name='部門')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegisterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_hour', models.IntegerField(verbose_name='開始時間')),
                ('end_hour', models.IntegerField(verbose_name='終了時間')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='自動生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終編集者')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.staff', verbose_name='担当者')),
            ],
            options={
                'verbose_name': 'レジシフト枠',
                'verbose_name_plural': 'レジシフト枠',
                'ordering': ['date', 'start_hour'],
                'unique_together': {('date', 'start_hour')},
            },
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='編集日時')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='編集者')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.registerslot', verbose_name='対象枠')),
                ('new_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to='register.staff', verbose_name='変更後')),
                ('previous_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to='register.staff', verbose_name='変更前')),
            ],
            options={
                'verbose_name': '編集履歴',
                'verbose_name_plural': '編集履歴',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_hour', models.IntegerField(default=10, verbose_name='出勤時間')),
                ('end_hour', models.IntegerField(default=19, verbose_name='退勤時間')),
                ('shift_type', models.CharField(choices=[('早', '早番'), ('遅', '遅番'), ('流早', '流し早番'), ('流遅', '流し遅番'), ('通し', '通し'), ('その他', 'その他')], default='早', max_length=10, verbose_name='シフト種別')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '出勤情報',
                'verbose_name_plural': '出勤情報',
                'ordering': ['date', 'start_hour'],
                'unique_together': {('date', 'staff')},
            },
        ),
    ]
