# Generated by Django 6.0 on 2025-12-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'ordering': ['date', 'start_hour', 'start_min'], 'verbose_name': '出勤情報', 'verbose_name_plural': '出勤情報'},
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='end_min',
            field=models.IntegerField(default=0, verbose_name='退勤時間（分）'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='start_min',
            field=models.IntegerField(default=0, verbose_name='出勤時間（分）'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='end_hour',
            field=models.IntegerField(default=19, verbose_name='退勤時間（時）'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='start_hour',
            field=models.IntegerField(default=10, verbose_name='出勤時間（時）'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('店長', '店長'), ('季節', '季節'), ('家電', '家電'), ('情報', '情報'), ('通信', '通信')], default='季節', max_length=20, verbose_name='部門'),
        ),
    ]
