# Generated by Django 6.0 on 2025-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_dailyattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'スタッフ', 'verbose_name_plural': 'スタッフ'},
        ),
        migrations.AddField(
            model_name='staff',
            name='display_order',
            field=models.IntegerField(default=9999, verbose_name='表示順'),
        ),
    ]
